language: cpp

sudo: false

matrix:
  include:
    - env: PAGMO_BUILD="DebugGCC48"
      compiler: gcc
      os: linux
      addons:
        apt:
          sources:
          - ubuntu-toolchain-r-test
          packages:
          - gcc-4.8
          - g++-4.8
          - binutils-gold
    - env: PAGMO_BUILD="ReleaseGCC48"
      compiler: gcc
      os: linux
      addons:
        apt:
          sources:
          - ubuntu-toolchain-r-test
          packages:
          - gcc-4.8
          - g++-4.8
          - binutils-gold
    - env: PAGMO_BUILD="CoverageGCC5"
      compiler: gcc
      os: linux
      addons:
        apt:
          sources:
          - ubuntu-toolchain-r-test
          packages:
          - gcc-5
          - g++-5
          - binutils-gold
    - env: PAGMO_BUILD="DebugGCC6"
      compiler: gcc
      os: linux
      addons:
        apt:
          sources:
          - ubuntu-toolchain-r-test
          packages:
          - gcc-6
          - g++-6
          - binutils-gold
    - env: PAGMO_BUILD="DebugClang38"
      compiler: clang
      os: linux
      addons:
        apt:
          sources:
          - llvm-toolchain-precise-3.8
          - ubuntu-toolchain-r-test
          packages:
          - clang-3.8
    - env: PAGMO_BUILD="ReleaseClang38"
      compiler: clang
      os: linux
      addons:
        apt:
          sources:
          - llvm-toolchain-precise-3.8
          - ubuntu-toolchain-r-test
          packages:
          - clang-3.8

script:
    - mkdir build
    - cd build
    - source ../tools/install_deps.sh
    - source ../tools/install_travis.sh