#environment:
#  TWINE_PASSWORD:
#    secure: fqy2DKVE2zM+97vNPB8xgw3ae3SDPkL/T8RvC6s4ncY=
#  matrix:
#    - BUILD_TYPE: "MSVC_64_Python36"
#      COMPILER: MSVC15
#      PLATFORM: "x64"
#    - BUILD_TYPE: "MSVC_64_Release"
#      COMPILER: MSVC15
#      PLATFORM: "x64"
#    - BUILD_TYPE: "MinGW_64_Debug"
#    - BUILD_TYPE: "MinGW_64_Python27"
#    - BUILD_TYPE: "MinGW_64_Python35"
#    - BUILD_TYPE: "MinGW_64_Python36"
#  global:
#    PLATFORMTOOLSET: "v140"
# 
#install:
#- if [%BUILD_TYPE%]==[MSVC_64_Release] set PATH=C:\Miniconda36-x64\Scripts;%PATH%
#- if [%BUILD_TYPE%]==[MSVC_64_Release] conda config --add channels conda-forge --force
#- if [%BUILD_TYPE%]==[MSVC_64_Release] conda create -y --name pagmo_plugins_nonfree python=3.6 cmake boost eigen nlopt pagmo
## NOTE: need to use "call" because otherwise it won't work within an if block.
#- if [%BUILD_TYPE%]==[MSVC_64_Release] call activate pagmo_plugins_nonfree
#
#- if [%BUILD_TYPE%]==[MSVC_64_Python36] set PATH=C:\Miniconda36-x64\Scripts;%PATH%
#- if [%BUILD_TYPE%]==[MSVC_64_Python36] conda config --add channels conda-forge --force
#- if [%BUILD_TYPE%]==[MSVC_64_Python36] conda create -y --name pagmo_plugins_nonfree python=3.6 cmake boost eigen nlopt pagmo pygmo
#- if [%BUILD_TYPE%]==[MSVC_64_Python36] call activate pagmo_plugins_nonfree
#
## Rename sh.exe as sh.exe in PATH interferes with MinGW.
#- if [%BUILD_TYPE%]==[MinGW_64_Debug] rename "C:\Program Files\Git\usr\bin\sh.exe" "sh2.exe"
#- if [%BUILD_TYPE%]==[MinGW_64_Python27] rename "C:\Program Files\Git\usr\bin\sh.exe" "sh2.exe"
#- if [%BUILD_TYPE%]==[MinGW_64_Python35] rename "C:\Program Files\Git\usr\bin\sh.exe" "sh2.exe"
#- if [%BUILD_TYPE%]==[MinGW_64_Python36] rename "C:\Program Files\Git\usr\bin\sh.exe" "sh2.exe"
#
#build_script:
#- if [%BUILD_TYPE%]==[MSVC_64_Release] mkdir build
#- if [%BUILD_TYPE%]==[MSVC_64_Release] cd build
#- if [%BUILD_TYPE%]==[MSVC_64_Release] cmake -G "Visual Studio 14 2015 Win64" -DCMAKE_BUILD_TYPE=Release -DPAGMO_PLUGINS_NONFREE_BUILD_TESTS=YES  ..
#- if [%BUILD_TYPE%]==[MSVC_64_Release] cmake --build . --config Release --target install
## NOTE: need to copy the dll into the directory considered as current by ctest
#- if [%BUILD_TYPE%]==[MSVC_64_Release] cp tests\Release\snopt7_c.dll tests\
#- if [%BUILD_TYPE%]==[MSVC_64_Release] cp tests\Release\worhp_c.dll tests\
#
#- if [%BUILD_TYPE%]==[MSVC_64_Python36] mkdir build
#- if [%BUILD_TYPE%]==[MSVC_64_Python36] cd build
#- if [%BUILD_TYPE%]==[MSVC_64_Python36] cmake -G "Visual Studio 14 2015 Win64" -DCMAKE_INSTALL_PREFIX=%CONDA_PREFIX%/Library -DCMAKE_BUILD_TYPE=Release -DPAGMO_PLUGINS_NONFREE_HEADERS=no -DPAGMO_PLUGINS_NONFREE_BUILD_PYTHON=yes -DPAGMO_PLUGINS_NONFREE_BUILD_TESTS=No ..
#- if [%BUILD_TYPE%]==[MSVC_64_Python36] cmake --build . --config Release --target install
#
#
#- if [%BUILD_TYPE%]==[MinGW_64_Debug] C:\Python36-x64\python.exe tools\install_appveyor_mingw.py
#- if [%BUILD_TYPE%]==[MinGW_64_Python27] C:\Python36-x64\python.exe tools\install_appveyor_mingw.py
#- if [%BUILD_TYPE%]==[MinGW_64_Python35] C:\Python36-x64\python.exe tools\install_appveyor_mingw.py
#- if [%BUILD_TYPE%]==[MinGW_64_Python36] C:\Python36-x64\python.exe tools\install_appveyor_mingw.py
#
#test_script:
#- if [%BUILD_TYPE%]==[MSVC_64_Release] ctest --output-on-failure
#
#- if [%BUILD_TYPE%]==[MSVC_64_Python36] cd ..
#- if [%BUILD_TYPE%]==[MSVC_64_Python36] cd tools
#- if [%BUILD_TYPE%]==[MSVC_64_Python36] Powershell.exe -File start_ip_cluster.ps1
#- if [%BUILD_TYPE%]==[MSVC_64_Python36] timeout 20
#- if [%BUILD_TYPE%]==[MSVC_64_Python36] python -c "import pygmo_plugins_nonfree as pg7; pg7.test.run_test_suite(1)"
#
#artifacts:
#  - path: build\wheel\dist
#    name: wheels
#
#notifications:
#  - provider: Webhook
#    url: https://webhooks.gitter.im/e/1a3742192bd3f7e6d8e2
#
## Enable this to be able to login to the build worker. You can use the
## `remmina` program in Ubuntu, use the login information that the line below
## prints into the log.
##on_finish:
##  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))